### PR TITLE
224: validate PolymorphicModels

### PR DESCRIPTION
**Pull request by LyricL-Gitster**
Fixes https://github.com/jrochkind/attr_json/issues/224

### CODE REVIEW

**Comment by LyricL-Gitster** [comment]
i didn't take the time to install PG on my machine, so I couldn't run the tests locally. I do, however, have a similar instance set up in another project, so hopefully I was able to write the specs up correctly.

**Comment by jrochkind** [comment]
Lovely thank you!

I will merge and release today or tomorrow!

I appreciate it, thanks!

**Comment by LyricL-Gitster** [comment]
OK, I actually installed PG to run the specs locally and figured out my bad reference in the new test. All's passing now! Thanks for the quick replies and all your effort on the gem!

**Comment by jrochkind** [comment]
ooh, you even added to the CHANGELOG, thank you!  I or you should add credit to @LyricL-Gitster  there -- I want to give you credit, plus it's good to show that people other than me are even occasionally contributing code!

**Comment by jrochkind** [comment]
oops, just remebered I forgot to come back to this after I left it with CI still running last week! Sorry! Merging and releasing today!

**Comment by jrochkind** [comment]
2.3.1 released with this fix! Thank you very much @LyricL-Gitster

**Comment by LyricL-Gitster** [comment]
Sure thing! Glad to help.

**Pull request merged**
