### PR TITLE
add #jsonb_contains_not

### PR DESCRIPTION
**Pull request by JochenLutz**
Add #jsonb_contains_not for negated json attribute queries

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks! I guess there's no way to put this together yourself with ActiveRecord `not`, you can't do like `Model.not.jsonb_contains`. Hmm. 

I'm getting a little bit suspect of this whole approach, the `jsonb_contains` API at all. Should we just have people write a where clause themselves in terms of postgres jsonb operations (like `->` and `->>`) themselves?   I have not ended up using `jsonb_contains` myself, I often need things outside of what it covers, and just write `where` clauses myself with postgres jsonb operators. At least I should prob make the docs give such examples, and say that you don't need jsonb_contains. 

But your code is nicely written and documented and tested, thanks!  If this is useful to you we can probably put it in. What is your use case for this? I'd imagine you'd get back a LOT of records?  I haven't ever needed to do this either.

**Comment by jrochkind** [comment]
(Also curious how you found out about attr_json @JochenLutz and how you are using it? But happy to see more people in the github issues!)

**Comment by jrochkind** [comment]
Some of the test failures look like unrelated infrastructure, not your responsibility. But some of the test failures seem to be your new tests of new func?

**Comment by JochenLutz** [comment]
We use that in an internal system, the table I needed this for has only ~ 440,000 rows. The table represents a recursive tree structure. We cache flattened ancestor data in an jsonb attribute (automatically updated by an ActiveJob) so speed up queries.

A colleague brought attr_json into our project, as a replacement for jsonb_accessor, which was not updated since 2017.

Your approach with `where("something -> 'other' = ?", value)` would be contrary to our policy "no SQL fragments in queries". So I do hope you continue to support `#jsonb_contains`. I especially like the automatic typecasting.

**Comment by jrochkind** [comment]
Ah, right you might not get the automatic typecasting with the manual `where`?

There are ALL SORTS of things you can do with postgres jsonb operators... like querying nested further down than one level, for instance. 

 think it's out of scope for this project to try to incorporate ALL of them with convenience abstraction syntax... I think if you want to take advantage of the full power of postgres's jsonb operators, you're going to have to be willing to write "SQL fragments". 

But even if we can't include everything, I guess maybe it makes sense to include `not`?  Let me think about it for a bit, hm. I'm definitely going to get decreasingly happy about any additional convenience methods though, heh. Want to minimize the maintenance burden of this code, since it's already a lot of tricky code, without a lot of people maintaining it. 

(You could always add your own class methods to your own models, of course, too!)

Thank you for the contribution!

Looks like I also may have to fix some unrelated broken parts of test infrastructure.

**Comment by JochenLutz** [comment]
I have not checked all Travis output, but it seems that on CI, attr_json generates `WHERE (NOT ...`, while on my local system, I got `WHERE NOT ...` (without the parenthesis around `NOT`).

I changed it to regexp matching.

**Comment by jrochkind** [comment]
> I have not checked all Travis output, but it seems that on CI, attr_json generates WHERE (NOT ..., while on my local system, I got WHERE NOT ... (without the parenthesis around NOT).

Gotta be different versions of Rails, I'd think? We currently support/test all the way back to Rails 5.0, and up to 6.0 and edge.

**Comment by JochenLutz** [comment]
> Gotta be different versions of Rails, I'd think? We currently support/test all the way back to Rails 5.0, and up to 6.0 and edge. What version were you testing on locally?

I used Rails 6.0.3.1 (from Gemfile.lock, without changes).

With the fixed tests, all failures are now from `form_mega_spec.rb`.

**Comment by jrochkind** [comment]
There isn't actually a `Gemfile.lock` in the repo (as my current understanding of best practices for gem development), so that wasn't from a repo Gemfile.lock. But we should be testing in latest 6.0.x. 

Odd, not sure why travis would be different than your local one. 

Anyway, thanks! I will probably merge this, but give me a bit of time to sit on it. Please feel free to ping me if it's next week and nothing has happened. 

Unrelated test failures won't stop me from merging this, but I will want to get them fixed before a release.

**Comment by jrochkind** [comment]
I have master passing, would you mind merging and/or rebasing? (either way I don't care).

**Comment by JochenLutz** [comment]
> I have master passing, would you mind merging and/or rebasing? (either way I don't care).

Done. All tests pass now.

**Comment by JochenLutz** [comment]
It's now a week, so: ping
Any news on how/when you will merge this PR?

**Comment by jrochkind** [comment]
Thanks for the ping. OK, sure, why not. I'm nervous about feature creep and additional maintenance burden, but if it's useful to you, I don't want to drive away any users, and your code is clean and tested, thanks! 

Will merge and release a minor version now.

**Comment by jrochkind** [comment]
Hey @JochenLutz , before I actually do the release and make it final, please confirm -- `jsonb_contains_not` makes more sense to you as a method name than `not_jsonb_contains`?  I really would have picked `not_jsonb_contains`, do you have a reason to prefer the former?

**Comment by JochenLutz** [comment]
`not_jsonb_contains` is also ok for me, I don't have a preference. It actually is closer to SQL syntax.
Shall I change the pull request or do you do the edit?

**Comment by jrochkind** [comment]
Thanks! I already merged into master, so too late to change this pull request. You could do another pull request to change the name from master, or I could do it, probably next week.

**Comment by jrochkind** [comment]
@JochenLutz 1.1.0 released with `not_jsonb_contains`. Thanks for your interest and contribution!

**Pull request merged**
