### PR TITLE
Allow active record 7.0 through 7.1.pre

### LINKED ISSUE #134: Rails 7 support
It looks like attr_json is working great on Rails 7, but the gemspec still requires activerecord < 7.0. Would it be possible to drop the upper limit entirely?

### PR DESCRIPTION
**Pull request by jrochkind**
Closes #134
*  test CI under Rails 7.0.0
*  prepare for 1.4.0 release with 7.0.0 allowed in gemspec

### CODE REVIEW

**Comment by jrochkind** [comment]
Hm, we are getting a test failure when we run CI on Rails 7.0.0. Which is odd, because CI has been passing on Rails edge, why would it fail on Rails 7.0.0?

It is probably just a test setup issue of some kind. But I'm really on vacation, I may not have time to look at it until January, sorry! 

If anyone else reading wants to figure it out and make an alternate PR based, feel free! But I'll get it to in January.

**Comment by Bramjetten** [comment]
You're missing `sprockets-rails` from the Rails 7.0 Gemfile since it's no longer a dependency of Rails.

**Comment by jrochkind** [comment]
Thanks! Yep, making progress!

**Comment by Bramjetten** [comment]
Thanks a lot for your quick response 🙏

**Comment by jrochkind** [comment]
OK attr_json 1.4.0 released, with gemspec allowing Rails 7.0.0. Also we now run CI for Rails 7.0.0.

**Pull request merged**
