### PR TITLE
Allow Rails 7 alpha

### PR DESCRIPTION
**Pull request by pustomytnyk**
Since it's already tested with Appraisals.

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks!

I'm a little bit nervous to allow 7.0.0 final when it's not even out yet... I think if we change it to `< 7.0`, it will actually allow 7.0 pre-releases *if* you specifically add `gem "attr_json", "7.0.0.alpha1"` or something like that in your app Gemfile. (Bundler is weird with pre-releases). 

What do you think about that instead?  And then do you need a release of attr_json with that change, or are you using directly from github?

**Comment by pustomytnyk** [comment]
For me directly from github is fine (like any solution that would not require forking).

**Comment by jrochkind** [comment]
@pustomytnyk I tried doing alternate `< 7.0` in master branch, which I think will allow 7.0 pre-releases, but not actually upcoming 7.0.0 final release, which is my preferred solution until 7.0.0 is out and tested. 

Can you tell me if what's in master branch now works for you?  Thank you!

**Comment by pustomytnyk** [comment]
Yes, it works!

**Pull request closed without merging**
