### PR TITLE
test that casting to and from json type works correctly

### PR DESCRIPTION
**Pull request by nhemsley**
This adds a single test that casting to & from a json type works correctly.

### CODE REVIEW

**Comment by nhemsley** [comment]
I really havent had enough time to check that I have made the right assumptions, and to get my head around the json_attr code.

Please look at this as a preliminary patch to test :json type functionality.

Any thoughts appreciated. There is probably a slew of (attribute validation?) related tests, but this would seem to handle the simple case of shoving arbitrary hash data into a json_attr attribute.

**Comment by nhemsley** [comment]
This appears to fail pre rails 5.2 in travis.

**Comment by jrochkind** [comment]
Thanks, this is helpful, I'll find some time to take a look!

**Comment by nhemsley** [comment]
OK, I have been doing some debugging, replicating the travis build environment.

The cause of this is the fix to https://github.com/jrochkind/attr_json/issues/41.

So pre-rails-5.2 the type lookup:

 type = ActiveRecord::Type.lookup(type, adapter: nil)

fails because the :json type is postgres adaptor specific.

Not sure why it doesnt fail in rails 5.2. I will look into this now and update.

**Comment by nhemsley** [comment]
rails 5.2 has the :json type registered without an adapter (as well as the adapter specific type).

I'd say the commit that enables an adapter-less lookup is this one:

https://github.com/rails/rails/commit/1c4be603c121a8853a4f1d6c13cb91f9b66bef9e#diff-6764032bd285660fa20a2849e8dc81ef

But i'm a little over my head on this one.

perhaps just disabling this pre rails 5.2 in the test. and only enabling json types in rails 5.2+ (reflected in docs).

**Comment by jrochkind** [comment]
I haven't looked yet, but after thinking about it,  I'm worried that the `:json` type, where it does work, may be storing as a serialized string key. Like `some_json: "{ \"some_key\": \"some_value\"}"`

If that makes any sense. If it's doing that anyway, not worth trying to fix in more recent Rails anyway. We'd want a different solution instead, anyway. 

Can you confirm or deny that it's doing that in the Rails versions where it does work?

**Comment by nhemsley** [comment]
INSERT INTO "products" ("json_attributes") VALUES ($1) RETURNING "id"[0m  [["json_attributes", "{\"value\":\"{\\\"a\\\":\\\"b\\\",\\\"b\\\":{\\\"c\\\":\\\"d\\\"}}\"}"]]

as opposed to 

INSERT INTO "products" ("json_attributes") VALUES ($1) RETURNING "id"[0m  [["json_attributes", "{\"value\":true}"]]

**Comment by nhemsley** [comment]
I think you are correct, it is storing the 'value' as a string.

I will leave this open. Please close for now, unless you have any ideas on how to stop it escaping.

Cheers

**Comment by jrochkind** [comment]
Thanks for investigating!

So I don't think `:json` is the right path after all. 

I think we need an ActiveModel type that... basically just doesn't do anything. It's cast/serialize/deserialize methods all just return the argument passed in. 

That will allow you to set _anything_ that can be automatically converted to json, and have it work. I think. But it won't allow you to "set" the string serialized representation of a Hash -- because how could we tell the difference between something you meant to set as a string, and something you meant to set as a Hash?

Alternately, I suppose we could create a Type that assumes the value _must_ be a hash (and... raises if it's not?), which could also cast from a string-serialized Hash to a Hash. 

I'm not totally sure what best meets actual use cases. Perhaps the first very simple "no op" Type is the first thing to try. Do you have a use case yourself @nhemsley ?

**Comment by nhemsley** [comment]
Hey,

Haha, after stepping around the code and understanding attr_json better (and rails types), I came to this exact same conclusion. and was going to at some point have a look if you agreed.

I have spent too much time as is, however I will maybe have a look tomorrow. 

Thanks for the pointers, very much helpful.

**Comment by jrochkind** [comment]
Thanks for your contributions! No rush. I'll get to this eventually, if nobody else does.

**Comment by nhemsley** [comment]
So it seems the no-op case works fine (for my use case).

I am happy with having to set the value to a hash, and not a string-representation of the hash.

At the end, something like the following works:
``
#subclassing Value works as the serialize/deserialize is a no-op
class JsonHash < ActiveModel::Type::Value
end

ActiveRecord::Type.register(:json_hash, JsonHash)

class MyModel < ActiveRecord::Base
  include AttrJson::Record

  attr_json :data_dump, :json_hash
end

```
or 

```
class MyModel < ActiveRecord::Base
  include AttrJson::Record

  attr_json :data_dump, ActiveModel::Type::Value.new
end

```
An update on the readme would suffice 

OR add a new :json_hash type to attr_json, and register it with activeRecord somewhere in the setup code for attr_json.

**Comment by jrochkind** [comment]
Oh nice, you can actually just use straight `ActiveModel::Type::Value.new`, don't even need to define a subclass with any implementation? That makes sense. And is kinda neat.

**Comment by nhemsley** [comment]
Yes, it appears so. If the type is an instance, then it just uses that.

**Comment by nhemsley** [comment]
As long as it is_a? ActiveModel::Type::Value

```
elsif ! type.is_a? ActiveModel::Type::Value
        raise ArgumentError, "Second argument (#{type}) must be a symbol or instance of an ActiveModel::Type::Value subclass"

```

**Comment by jrochkind** [comment]
Yep, I definitely know i wrote it to take ActiveModel::Type instances (which is how the underlying ActiveModel/ActiveRecord type API works).  It didn't occur to me that `ActiveModel::Type.new` was already a suitable "no-op" type. Neat.

**Comment by nhemsley** [comment]
OK, I'll close this off and add some docs to the readme.

Cheers, it has been an interesting learning process

**Pull request closed without merging**
