### PR TITLE
Ensure AttrJson default configs can be set globally

### PR DESCRIPTION
**Pull request by volkanunsal**
I use a different name for my jsonb column. Having to specify this everywhere I use `attr_json` was a drag, so I created a global configuration to specify default value for this column.

### CODE REVIEW

**Comment by jrochkind** [comment]
Hi, you can already do this on a model-specific basis with: `attr_json_config(default_container_attribute: :some_other_column_name)`

Would it suffice to give all your models a common superclass, so you could set the defaults you want in that common superclass?

Alternatively, what if you write your own `ActiveSupport::Concern` module that sets the defaults you want, say called `MyDefaults`, and `include` it in all your model classes?

If these would not suffice, I need to look at the code and think about it more. One of the dangers of truly "global" defaults is that they will apply to code in _other gems_, code written by other people. By changing a global default, you can invisibly change the behavior of already existing code written by someone else, so long as it is running in your process, which can be a confusing and dangerous thing to do. I made the choice to avoid global defaults if possible, in favor of class-specific configuration, with the idea you could use standard ruby OO techniques (inheritance, or a mix-in that sets configuration) to control it yourself, in a more visible and transparent way.

**Comment by jrochkind** [comment]
```ruby
module MyDefaults
  extend ActiveSupport::Concern
  included do
    attr_json_config(default_container_attribute: :some_other_column_name)
  end
end

class MyModel < ApplicationRecord
  include AttrJson::Record
  include MyDefaults
  # ...
end
```

I suppose you could even do:

```ruby
module MyCustomizedAttrJsonRecord
  extend ActiveSupport::Concern
  include AttrJson::Record
  
  included do
    attr_json_config(default_container_attribute: :some_other_column_name)
  end
end

class MyModel < ApplicaitonRecord
  include MyCustomizedAttrJsonRecord
  
  attr_json # ...
  # ...
end
```

**Comment by volkanunsal** [comment]
You're right. I could probably add `attr_json_config(default_container_attribute: :some_other_column_name)` in ApplicationRecord. 

But I was also thinking that a global config would be useful for the merge feature I'm hacking on. I think that can't be handled on a case by case basis.

**Comment by jrochkind** [comment]
I agree `ApplicationRecord` isn't ideal because it would require you add `AttrJson::Record` to `ApplicationRecord`, and you might only want it in some models. 

But you can do a `ApplicationJsonRecord` that all your `AttrJson::Record`s descend from, which seems a decent solution to me. Or you can use the `include MyLocalConfiguration` approach I outlined too. 

Both of those seem like decent solutions. 

I'm not following how it's needed/useful for the merge feature. Even if there was global configuration of the container attribute, the merge feature should *not* be using it, as individual models may configure something different than the hypothetical global anyway. So the merge feature has got to be looking at the individual model class anyway, if it needs to know the container attribute. 

But I'm thinking the merge feature shouldn't need to know the container attribute anyway? It should ideally be somewhat decoupled from `AttrJson::Record`, ideally the merge feature would let you apply merge-updates to a Jsonb column whether or not you are using `AttrJson::Record` on the model, yeah?  And ideally it would be opt-in to a given column (perhaps by specifying a custom `ActiveRecord::Type` that triggers the update-merge behavior?

I am definitely leaning against global defaults for container attribute or other attr_config, they seem unneccesary complexity. I'm not seeing how they are related to the update-merge feature, and the update-merge feature ideally should not rely on attr_json config either.

**Comment by volkanunsal** [comment]
Ah, I see your point.

**Pull request closed without merging**
